name: smart_locker_komisaris_new
description: A new Flutter project
homepage: https://github.com/devsayed-spec/project-tugas-akhir

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_database: ^11.3.6
  mqtt_client: ^10.0.0
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"